spring:
  application:
    name: service-contract-config-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: onepdl
logging:
  level:
    root: INFO
server:
  port: 8022