spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        input:
          binder: kafka
          destination: greetings
          content-type: application/json
          group: input-group-1
        output:
          binder: kafka
          destination: greetings
          content-type: application/json
          group: output-group-1        
