spring:
  application:
    name: kafka-consumer-service
  kafka:
    bootstrap-servers: localhost:29092  
    consumer:      
      group-id: consumer-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer  
    properties:
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true
logging:
  level:
    root: INFO
server:
  port: 8022
  
kafka.topic.name: sample.producer.avro.topic